### ISSUE TITLE
Panic when @kinds line ends in a space

### ISSUE THREAD

**Issue by jalseth** [plexsystems/konstraint#68]
If the `@kinds` line in the header block ends in a space, the `konstraint doc` command panics. This should be trimmed before splitting on the space character to avoid this.

```
$ konstraint doc policy -o policies.md                   
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/plexsystems/konstraint/internal/commands.getKindMatchers(0xc00002ea50, 0x42, 0x17d2db2, 0x6, 0x1)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/gatekeeper.go:48 +0x29c
github.com/plexsystems/konstraint/internal/commands.GetMatchersFromComments(0xc00017f9e8, 0x1, 0x1, 0x6, 0x1, 0x17d1eb8)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/gatekeeper.go:24 +0x10c
github.com/plexsystems/konstraint/internal/commands.getHeader(0xc000154600, 0x6, 0x8, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/document.go:159 +0x590
github.com/plexsystems/konstraint/internal/commands.getDocumentation(0x7ffeefbff967, 0x6, 0x17d1e95, 0x1, 0xb, 0xc000192f60, 0x17d22ff)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/document.go:100 +0x1de
github.com/plexsystems/konstraint/internal/commands.runDocCommand(0x7ffeefbff967, 0x6, 0x3, 0x18b3a20)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/document.go:70 +0x79
github.com/plexsystems/konstraint/internal/commands.newDocCommand.func1(0xc0001aa000, 0xc0001931a0, 0x1, 0x3, 0x0, 0x0)
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/internal/commands/document.go:58 +0x293
github.com/spf13/cobra.(*Command).execute(0xc0001aa000, 0xc000193170, 0x3, 0x3, 0xc0001aa000, 0xc000193170)
        /Users/james/Code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001398c0, 0x0, 0xffffffff, 0xc000078058)
        /Users/james/Code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/james/Code/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/james/Code/go/pkg/mod/github.com/plexsystems/konstraint@v0.7.1/main.go:10 +0x2a
```

**Comment by jpreese** [comment]
Resolved via #69
